name: Upload Info

on:
  push:
    branches:
      - main

jobs:
  upload-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from JSON
        id: version
        run: |
          PROJECT=$(jq -r '.name' dytes.json)
          VERSION=$(jq -r '.version' dytes.json)

          if [[ -z "$PROJECT" || -z "$VERSION" ]]; then
            echo "ERROR: name or version empty in dytes.json"
            exit 1
          fi

          echo "project=$PROJECT" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload dytes.json to UpYun S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.UPYUN_API_KEY }}
          aws_secret_access_key: ${{ secrets.UPYUN_API_SECRET }}
          aws_bucket: ${{ secrets.UPYUN_BUCKET }}
          source_file: ./dytes.json
          destination_path: app/${{ steps.version.outputs.project }}.json
          endpoint: https://s3.api.upyun.com
